# GitHub Action para generar un gráfico de contribuciones con una serpiente comiéndose tus contribuciones.

name: Generate Snake

# Controla cuándo se ejecutará la acción. Esta acción se ejecuta cada 6 horas.

on:
  schedule:
    # cada 6 horas
    - cron: "0 */6 * * *"

  # Este comando permite ejecutar la Acción automáticamente desde la pestaña Acciones.
  workflow_dispatch:

# La secuencia de ejecuciones en este flujo de trabajo:
jobs:
  # Este flujo de trabajo contiene un solo trabajo llamado "build"
  build:
    # El tipo de corredor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo
    steps:

    # Comprueba el repositorio bajo $GITHUB_WORKSHOP, para que tu trabajo pueda acceder a él
      - uses: actions/checkout@v3

    # Genera la serpiente  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Joansitoh
          # estas siguientes 2 líneas generan los archivos en una rama llamada "output". Esto evita que la rama principal se llene de archivos.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # muestra el estado de la compilación. Facilita la depuración (si hay algún problema).
      - run: git status

      # Realiza los cambios
      - name: Push changes
        uses: ad-m/github-push-action@v1.0.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          # la rama de salida que mencionamos anteriormente
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
